### ISSUE TITLE
Got wrong message~

### ISSUE THREAD

**Issue by coloraven** [emendelson/pdftoprinter#1]
Try to print 10+ pdf files, and successed print about 7+ ,than got the wrong message blow,and the program didn't work normal.

I call the `pdftoprinter` in Python like this:
```python
....
filename = ....
pageflags = ...
import subprocess
args = ["pdftoprinter.exe",filename,pageflags]
subprocess.run(args)
....
```

![IMG_20231210_212328_edit_557781082245399](https://github.com/emendelson/pdftoprinter/assets/5030800/897b4af6-48ea-4378-91a7-bdc4e135ab9c)

**Comment by emendelson** [comment]
Which version of Windows?

**Comment by liujunwei4321** [comment]
Could you provide the PDF file that raised the error?

**Comment by emendelson** [comment]
With no reply after two months, it's probably time to close this issue.
