### ISSUE TITLE
silent not work

### ISSUE THREAD

**Issue by jairforero** [emendelson/pdftoprinter#3]
Hi If I writte full path no work run silently and display array window, thanks

**Comment by emendelson** [comment]
@jairforero - Thank you for finding that. I forgot to comment out a line that I used when testing. It is fixed now.

**Comment by furnaceX** [comment]
I'm having trouble getting the silent /s mode to work:
Windows 10:
PowerShell: Start-Process -FilePath "C:\Scott\scripts\PDFtoPrinter.exe" -ArgumentList 'shipping_documents_4_x_6.pdf /s' -WindowStyle Hidden -Wait

Or standard command line:
c:\Scott\scripts\PDFtoPrinter.exe /s shipping_documents_4_x_6.pdf

Also, if I hit "cancel" in the window, it still prints.
