### ISSUE TITLE
Running printToPDF using CMD

### ISSUE THREAD

**Issue by arifinreinaldo** [emendelson/pdftoprinter#4]
Hi,
I'm trying to create function to call printing by getting the filename information from database and then using the C# I will call the printToPDF exe to print the file with the parameter "File Name" and "Printer name" being used.

If I print this using only 1 scheduler it doesn't have any issue, but if I print this using more than 1 scheduler, the spool will add duplicate to the spool. Any clue as to fix this issue? or Information that need to be gathered more? Thank you

**Comment by emendelson** [comment]
@arifinreinaldo - That part of the code was written by someone else who wants to remain anonymous (and I don't know that person's name), so I have no idea of how to use it. Please feel free to look at the code to see if you can find any way to fix it. If so, I will be glad to add it to the code here.

One other point: you may not need this program at all. Powershell can print PDF files from the command line. The syntax is something like this:

`Start-Process -FilePath "path\to\file" -Verb PrintTo -ArgumentList "Name of Printer" -PassThru | %{sleep 10;$_} | kill`

I didn't figure this out for myself; a helpful expert on stackoverflow.com helped me to get it right.
