### ISSUE TITLE
EXE cleaned by Bitdefender

### ISSUE THREAD

**Issue by jeanfvoyer** [emendelson/pdftoprinter#6]
Bitdefender is telling me that this EXE file is a MALWARE :

On-Access scanning has detected a threat. The file has been deleted. PDFtoPrinter.exe is malware of type Trojan.GenericKD.71597464

Am I the only one to encounter this problem?

P.S. I Have ESET on my developement computer and did not encounter this problem.

Thanks.

**Comment by emendelson** [comment]
@jeanfvoyer -  I've added a paragraph about this to this page:

https://mendelson.org/pdftoprinter.html

I'll also add it to the GitHub page.

**Comment by jeanfvoyer** [comment]
@emendelson thanks and sorry I didn't get to that point in the article

**Comment by emendelson** [comment]
@jeanfvoyer
