### ISSUE TITLE
An error is reported, what should I do?

### ISSUE THREAD

**Issue by fdjkdf** [emendelson/pdftoprinter#8]
DllOpenO error: Can't open C:\Users\admin\AppData\Local\Temp\PDFPrinterTmp\qpdf28 dll.

xx.pdf: getPageCount() error, pdf file Corrupted?

**Comment by emendelson** [comment]
1. You did not specify the command that produced that error.

2. I did not write the part of the code that uses qpdf28.dll, so I probably will not know the answer.

3. I strongly recommend that you use a different program for printing PDF files, because this one causes problems for you.

**Comment by felps-dev** [comment]
I found out the problem, it's because qpdf has dependency on latest MSVCP dll's, and the PDFtoPrinter does not bundle them together.
https://github.com/emendelson/pdftoprinter/pull/10

**Comment by emendelson** [comment]
Good - thank you!

**Comment by fdjkdf** [comment]
> 我发现了问题，这是因为 qpdf 依赖于最新的 MSVCP dll，而 PDFtoPrinter 没有将它们捆绑在一起。 #10

You are awesome! 

I would also like to ask, do you know how to solve this problem? How to print multiple copies of a document?
https://github.com/emendelson/pdftoprinter/issues/7

**Comment by emendelson** [comment]
Please read the entire thread in https://github.com/emendelson/pdftoprinter/issues/7

**Comment by NikkiePleasure** [comment]
Solved the problem by installing MicrosoftVisualCppRedistributable\2015.x-x86\2022-14.42.34433-x86\vc_redist.x86.exe

**Comment by emendelson** [comment]
@NikkiePleasure - Which problem was that?

**Comment by NikkiePleasure** [comment]
> @NikkiePleasure - Which problem was that?

Problem with missing dll. "DllOpenO error: Can't open C:\Users\admin\AppData\Local\Temp\PDFPrinterTmp\qpdf28 dll."
I added it to my comment above
